quarkus:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    reactive:
      url: mysql://${MYSQL_DOMAIN}/db_menu_options

configuration:
  rest-clients:
    product-v1:
      request:
        endpoint: http://${PRODUCT_DOMAIN}/poc/business/product/v1/