name: table-placement-v1
image:
  repository: miguelarmasabt/table-placement
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8013
  nodePort: 30013
replicas: 1

configMaps:
  CONFIG_SERVER_DOMAIN: "config-server-v1:8888"
  JAVA_OPTS: "-Xms256M -Xmx256M"

secrets:
  MONGODB_URL: "mongodb://bbq-user:qwerty@mongo-db:27017/tablePlacement"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8013
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8013
  initialDelaySeconds: 60
  periodSeconds: 30

namespace: restaurant
helmTemplate: with-health

docker:
  hostPort: 8013
  dependencies: config-server-v1;mongo-db
  volumes: none