server:
  port: ${SERVER_PORT:8011}

spring:
  application:
    name: auth-adapter-v1

configuration:
  project-type: MS

  keycloak:
    base-url: http://${KEYCLOAK_DOMAIN:localhost:8091}/auth/realms/bbq-management/protocol/openid-connect/
    client-id: front-bbq-app
    grant-type: password
    client-secret: qwerty
    scope: profile
    auth-endpoint: ${configuration.keycloak.base-url}auth
    jwk-endpoint: ${configuration.keycloak.base-url}certs
    cert-id: ${KEYCLOAK_KEY_RS256:cYUJGhUPamPjsFL8K12AF3H7AsB46WX8Yty48f05Sa0}

  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.
    ExpiredToken: Ocurrió un error durante la autenticación.
    InvalidJWT: Ocurrió un error durante la autenticación.

  rest-clients:
    auth-token:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: ${configuration.keycloak.base-url}
        form-data:
          client_id: ${configuration.keycloak.client-id}
          grant_type: ${configuration.keycloak.grant-type}
          client_secret: ${configuration.keycloak.client-secret}
          scope: ${configuration.keycloak.scope}
        headers:
          provided:
            Accept: application/json

    refresh-token:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: ${configuration.keycloak.base-url}
        form-data:
          client_id: ${configuration.keycloak.client-id}
          grant_type: ${configuration.keycloak.grant-type}
        headers:
          provided:
            Accept: application/json

    user-info:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: ${configuration.keycloak.base-url}
        headers:
          provided:
            Accept: application/json
          forwarded:
            Authorization: Authorization

    logout:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: ${configuration.keycloak.base-url}
        form-data:
          client_id: ${configuration.keycloak.client-id}
          grant_type: ${configuration.keycloak.grant-type}
        headers:
          provided:
            Accept: application/json

# actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, beans, env, loggers, flyway
  endpoint:
    health:
      show-details: always
      probes: #livess & readiness probe
        enabled: true