---
# Source: generic-server-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-server-secret
type: Opaque
data:
    KEYCLOAK_PASSWORD: "YWRtaW4="
---
# Source: generic-server-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-server-config-map
data:
    DB_VENDOR: "H2"
    KEYCLOAK_USER: "admin"
---
# Source: generic-server-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: keycloak-server
  labels:
    app: keycloak-server
spec:
  type: NodePort
  selector:
    app: keycloak-server
  ipFamilies:
    - IPv4
  ports:
    - name: keycloak-server
      port: 8080
      nodePort: 30180
---
# Source: generic-server-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-server
  labels:
    app: keycloak-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-server
  template:
    metadata:
      labels:
        app: keycloak-server
    spec:
      containers:
        - name: keycloak-server
          image: "jboss/keycloak:16.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          env:
              - name: DB_VENDOR
                valueFrom:
                  configMapKeyRef:
                    name: keycloak-server-config-map
                    key: DB_VENDOR
              - name: KEYCLOAK_USER
                valueFrom:
                  configMapKeyRef:
                    name: keycloak-server-config-map
                    key: KEYCLOAK_USER
              - name: KEYCLOAK_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: keycloak-server-secret
                    key: KEYCLOAK_PASSWORD
