---
# Source: generic-backend-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: menu-v2-secret
type: Opaque
data:
    MYSQL_PASSWORD: "cXdlcnR5"
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: menu-v2-config-map
data:
    JAVA_OPTS: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-profile=dev"
    MYSQL_DOMAIN: "mysql-db:3306"
    MYSQL_USERNAME: "bbq_user"
    PRODUCT_DOMAIN: "product-v1:8017"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: menu-v2
  labels:
    app: menu-v2
spec:
  type: NodePort
  selector:
    app: menu-v2
  ipFamilies:
    - IPv4
  ports:
    - name: menu-v2
      port: 8016
      nodePort: 30016
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-v2
  labels:
    app: menu-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-v2
  template:
    metadata:
      labels:
        app: menu-v2
    spec:
      containers:
        - name: menu-v2
          image: "miguelarmasabt/menu:v2.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8016

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8016
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8016
            initialDelaySeconds: 60
            periodSeconds: 30

          env:
              - name: JAVA_OPTS
                valueFrom:
                  configMapKeyRef:
                    name: menu-v2-config-map
                    key: JAVA_OPTS
              - name: MYSQL_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: menu-v2-config-map
                    key: MYSQL_DOMAIN
              - name: MYSQL_USERNAME
                valueFrom:
                  configMapKeyRef:
                    name: menu-v2-config-map
                    key: MYSQL_USERNAME
              - name: PRODUCT_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: menu-v2-config-map
                    key: PRODUCT_DOMAIN
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: menu-v2-secret
                    key: MYSQL_PASSWORD
