---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rules-processor-v1-config-map
data:
    CONFIG_SERVER_DOMAIN: "config-server-v1:8888"
    JAVA_OPTS: "-Xms256M -Xmx256M"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rules-processor-v1
  labels:
    app: rules-processor-v1
spec:
  type: NodePort
  selector:
    app: rules-processor-v1
  ipFamilies:
    - IPv4
  ports:
    - name: rules-processor-v1
      port: 8019
      nodePort: 30019
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rules-processor-v1
  labels:
    app: rules-processor-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rules-processor-v1
  template:
    metadata:
      labels:
        app: rules-processor-v1
    spec:
      containers:
        - name: rules-processor-v1
          image: "miguelarmasabt/rules-processor:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8019

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8019
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8019
            initialDelaySeconds: 60
            periodSeconds: 30

          env:
              - name: CONFIG_SERVER_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: rules-processor-v1-config-map
                    key: CONFIG_SERVER_DOMAIN
              - name: JAVA_OPTS
                valueFrom:
                  configMapKeyRef:
                    name: rules-processor-v1-config-map
                    key: JAVA_OPTS
