---
# Source: generic-backend-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: table-placement-v1-secret
type: Opaque
data:
    MONGODB_URL: "bW9uZ29kYjovL2JicS11c2VyOnF3ZXJ0eUBtb25nby1kYjoyNzAxNy90YWJsZVBsYWNlbWVudA=="
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: table-placement-v1-config-map
data:
    CONFIG_SERVER_DOMAIN: "config-server-v1:8888"
    JAVA_OPTS: "-Xms256M -Xmx256M"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: table-placement-v1
  labels:
    app: table-placement-v1
spec:
  type: NodePort
  selector:
    app: table-placement-v1
  ipFamilies:
    - IPv4
  ports:
    - name: table-placement-v1
      port: 8013
      nodePort: 30013
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-placement-v1
  labels:
    app: table-placement-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-placement-v1
  template:
    metadata:
      labels:
        app: table-placement-v1
    spec:
      containers:
        - name: table-placement-v1
          image: "miguelarmasabt/table-placement:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8013

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8013
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8013
            initialDelaySeconds: 60
            periodSeconds: 30

          env:
              - name: CONFIG_SERVER_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: table-placement-v1-config-map
                    key: CONFIG_SERVER_DOMAIN
              - name: JAVA_OPTS
                valueFrom:
                  configMapKeyRef:
                    name: table-placement-v1-config-map
                    key: JAVA_OPTS
              - name: MONGODB_URL
                valueFrom:
                  secretKeyRef:
                    name: table-placement-v1-secret
                    key: MONGODB_URL
