configuration:
  project-type: MS

  error-messages:
    Default: No hemos podido realizar tu operaci√≥n. Estamos trabajando para solucionar el inconveniente.

  rest-clients:
    payment-processor:
      performance:
        timeout: EXCELLENT
        concurrency: LOW
      request:
        endpoint: http://${MOCK_SERVICE_DOMAIN:localhost:8080}/external/payments/v1/
        headers:
          provided:
            Accept: application/x-ndjson
          generated:
            parent-id: PARENT_ID
            timestamp: TIMESTAMP
          forwarded:
            trace-id: trace-id
            channel-id: channel-id

  obfuscation:
    body-fields: []
    headers: []

kafka-broker:
  topic:
    invoice: invoice-topic
    payment: paid-topic

spring:
  kafka:
    bootstrap-servers: ${KAFKA_DOMAIN:localhost:9092}
    consumer:
      group-id: poc
    properties:
      spring:
        kafka:
          consumer:
            auto-offset-reset: earliest #latest
    admin:
      properties:
        spring.kafka.admin.properties:
          auto.create.topics.enable: ${CREATE_TOPICS:false}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_DOMAIN:127.0.0.1:3306}/db_payments?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:poc_user}
    password: ${MYSQL_PASSWORD:qwerty}