configuration:
  application-name: ${spring.application.name}

  error-messages:
    enabled: false
    messages:
      Default: No hemos podido realizar tu operaci√≥n. Estamos trabajando para solucionar el inconveniente.

  rest-clients:
    product-v1:
      request:
        endpoint: http://${PRODUCT_DOMAIN:localhost:8017}/bbq/business/product/v1/products/
        headers:
          provided:
            Accept: application/json
          generated:
            parentId: PARENT_ID
            timestamp: TIMESTAMP_V2
          forwarded:
            traceId: traceId

  variables:
    igv: 0.18

  obfuscation:
    body-fields: []
    headers: []
    header-obfuscation-type: {}

  rules:
    discount-rules:
      class-name: DiscountRule
      drool-file: discount_rules.drl

kafka-broker:
  topic:
    invoice: invoice-topic
    payment: paid-topic

spring:
  kafka:
    bootstrap-servers: ${KAFKA_DOMAIN:localhost:9092}
    consumer:
      group-id: bbq
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_DOMAIN:127.0.0.1:5432}/db_invoices?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME:bbq_user}
    password: ${POSTGRESQL_PASSWORD:qwerty}