spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_DOMAIN:127.0.0.1:3306}/db_menu_options?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:bbq_user}
    password: ${MYSQL_PASSWORD:qwerty}

configuration:
  show-custom-messages: false

  rest-clients:
    product-v1:
      request:
        endpoint: http://${PRODUCT_DOMAIN:localhost:8017}/bbq/business/product/v1/
        headers:
          provided:
            Accept: application/json
          generated:
            parentId: PARENT_ID
            timestamp: TIMESTAMP_V2
          forwarded:
            traceId: traceId

  errors:
    Default: No hemos podido realizar tu operaci√≥n. Estamos trabajando para solucionar el inconveniente.
