spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://bbq-user:qwerty@mongo-db:27017/tablePlacement}
#      uri: mongodb+srv://miguelarmasabt:l21m01j16M01L13@cluster0.t2pidzg.mongodb.net/tablePlacement

configuration:
  show-custom-messages: false

  errors:
    Default: No hemos podido realizar tu operaci√≥n. Estamos trabajando para solucionar el inconveniente.

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.netflix.config.sources.URLConfigurationSource: ERROR