configuration:
  error-messages:
    enabled: false
    messages:
      Default: No hemos podido realizar tu operaci√≥n. Estamos trabajando para solucionar el inconveniente.

  rest-clients:
    product-v1:
      request:
        endpoint: http://${PRODUCT_DOMAIN:localhost:8017}/bbq/business/product/v1/
        headers:
          provided:
            Accept: application/json
          generated:
            parentId: PARENT_ID
            timestamp: TIMESTAMP_V2
          forwarded:
            traceId: traceId

quarkus:
  datasource:
    db-kind: mysql
    username: ${MYSQL_USERNAME:bbq_user}
    password: ${MYSQL_PASSWORD:qwerty}
    jdbc: false
    reactive:
      url: mysql://${MYSQL_DOMAIN:localhost:3306}/db_menu_options
      max-size: 20
  hibernate-orm:
    log:
      sql: true
  rest-client:
    product-v1:
      url: ${configuration.rest-clients.product-v1.request.endpoint}
      verify-host: false

product-v1:
  mp-graphql:
    url: http://localhost:8017/graphql