---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-v1-config-map
data:
    auth-adapter-domain: "auth-adapter-v1:8011"
    enable-auth: "false"
    java-opts: "-Xms256M -Xmx256M"
    order-hub-domain: "order-hub-v1:8018"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-v1
  labels:
    app: api-gateway-v1
spec:
  type: NodePort
  selector:
    app: api-gateway-v1
  ports:
    - name: api-gateway-v1
      port: 8010
      nodePort: 30010
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-v1
  labels:
    app: api-gateway-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-v1
  template:
    metadata:
      labels:
        app: api-gateway-v1
    spec:
      containers:
        - name: api-gateway-v1
          image: "miguelarmasabt/api-gateway:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8010

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8010
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8010
            initialDelaySeconds: 30
            periodSeconds: 30

          env:
              - name: AUTH_ADAPTER_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: api-gateway-v1-config-map
                    key: auth-adapter-domain
              - name: ENABLE_AUTH
                valueFrom:
                  configMapKeyRef:
                    name: api-gateway-v1-config-map
                    key: enable-auth
              - name: JAVA_OPTS
                valueFrom:
                  configMapKeyRef:
                    name: api-gateway-v1-config-map
                    key: java-opts
              - name: ORDER_HUB_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: api-gateway-v1-config-map
                    key: order-hub-domain
